In [2]:
import numpy as np

In [3]:
arr=[1,2,3,4,5]

In [4]:
arrnp=np.array(arr)

In [49]:
arrnp

array([1, 2, 3, 4, 5])

In [6]:
arng=np.arange(0,500,10)

In [7]:
arng

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490])

In [58]:
listreshap=arng.reshape(5,10)

In [59]:
listreshap

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490]])

In [9]:
arng.argmax()

49

In [10]:
arng.argmin()

0

In [11]:
arng.max()

490

In [12]:
arng.min()

0

In [13]:
arng.mean()

245.0

In [14]:
arng.any()

True

In [15]:
arng.all()

False

In [16]:
arng.argpartition(1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)

In [17]:
arng.dtype

dtype('int32')

In [18]:
arng.item(20)

200

In [19]:
arng[arng>200]

array([210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330,
       340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460,
       470, 480, 490])

In [20]:
arng[0:5]

array([ 0, 10, 20, 30, 40])

In [21]:
arng.shape

(50,)

In [40]:
arrylist=[5,6,3,7,8]

In [41]:
arrnp * arrylist

array([ 5, 12,  9, 28, 40])

In [42]:
arrnp / arrylist

array([0.2       , 0.33333333, 1.        , 0.57142857, 0.625     ])

In [50]:
arrnp + arrylist

array([ 6,  8,  6, 11, 13])

In [44]:
arrnp - arrylist

array([-4, -4,  0, -3, -3])

In [53]:
arrnp * 100

array([100, 200, 300, 400, 500])

In [60]:
listreshap.sum()

12250

In [62]:
listreshap

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490]])

In [61]:
listreshap.sum(axis=0)

array([1000, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1450])

In [63]:
listreshap.sum(axis=1)

array([ 450, 1450, 2450, 3450, 4450])

In [ ]:
listreshap

In [24]:
rm1=np.random.rand(10)

In [25]:
rm1

array([0.2427745 , 0.69831027, 0.2640406 , 0.39264858, 0.37784875,
       0.33449073, 0.53832416, 0.5241963 , 0.0677216 , 0.89742477])

In [26]:
rm2=np.random.rand(2,10)

In [27]:
rm2

array([[0.19588476, 0.40621357, 0.92733339, 0.47718285, 0.86674457,
        0.80675132, 0.11832787, 0.83795964, 0.86728832, 0.38475408],
       [0.25444603, 0.14365485, 0.8661623 , 0.21930834, 0.15444949,
        0.44366346, 0.74358053, 0.13706412, 0.67515028, 0.89447931]])

In [28]:
rmInt=np.random.randint(1,500)

In [29]:
rmInt

118

In [30]:
zero=np.zeros((20))

In [31]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [32]:
one=np.ones((20))

In [33]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [34]:
np.linspace(1,70,20)

array([ 1.        ,  4.63157895,  8.26315789, 11.89473684, 15.52631579,
       19.15789474, 22.78947368, 26.42105263, 30.05263158, 33.68421053,
       37.31578947, 40.94736842, 44.57894737, 48.21052632, 51.84210526,
       55.47368421, 59.10526316, 62.73684211, 66.36842105, 70.        ])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])