In [1]:
import numpy as np

In [2]:
arr=[1,2,3,4,5]

In [3]:
arrnp=np.array(arr)

In [4]:
arrnp

array([1, 2, 3, 4, 5])

In [5]:
arng=np.arange(0,500,10)

In [6]:
arng

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490])

In [7]:
listreshap=arng.reshape(5,10)

In [8]:
listreshap

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490]])

In [9]:
arng.argmax()

49

In [10]:
arng.argmin()

0

In [11]:
arng.max()

490

In [12]:
arng.min()

0

In [13]:
arng.mean()

245.0

In [14]:
arng.any()

True

In [15]:
arng.all()

False

In [16]:
arng.argpartition(1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)

In [17]:
arng.dtype

dtype('int32')

In [18]:
arng.item(20)

200

In [19]:
arng[arng>200]

array([210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330,
       340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460,
       470, 480, 490])

In [20]:
arng[0:5]

array([ 0, 10, 20, 30, 40])

In [21]:
arng.shape

(50,)

In [22]:
arrylist=[5,6,3,7,8]

In [23]:
arrnp * arrylist

array([ 5, 12,  9, 28, 40])

In [24]:
arrnp / arrylist

array([0.2       , 0.33333333, 1.        , 0.57142857, 0.625     ])

In [25]:
arrnp + arrylist

array([ 6,  8,  6, 11, 13])

In [26]:
arrnp - arrylist

array([-4, -4,  0, -3, -3])

In [27]:
arrnp * 100

array([100, 200, 300, 400, 500])

In [28]:
listreshap.sum()

12250

In [29]:
listreshap

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490]])

In [30]:
listreshap.sum(axis=0)

array([1000, 1050, 1100, 1150, 1200, 1250, 1300, 1350, 1400, 1450])

In [31]:
listreshap.sum(axis=1)

array([ 450, 1450, 2450, 3450, 4450])

In [45]:
listreshap.std()

144.30869689661813

In [47]:
listreshap.var()

20825.0

In [33]:
rm1=np.random.rand(10)

In [34]:
rm1

array([0.49205556, 0.13271854, 0.1986171 , 0.06803917, 0.19773511,
       0.09179822, 0.72777172, 0.71547771, 0.53473269, 0.27176926])

In [35]:
rm2=np.random.rand(2,10)

In [36]:
rm2

array([[0.27717484, 0.69566617, 0.61663944, 0.34107161, 0.86386767,
        0.71263882, 0.60417136, 0.98016293, 0.15020437, 0.78084097],
       [0.0520153 , 0.58118727, 0.57615092, 0.04555914, 0.58215871,
        0.10647771, 0.66159953, 0.83780592, 0.14526689, 0.897706  ]])

In [37]:
rmInt=np.random.randint(1,500)

In [38]:
rmInt

47

In [39]:
zero=np.zeros((20))

In [40]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [41]:
one=np.ones((20))

In [42]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [60]:
linspace=np.linspace(1,3,5)
linspace

array([1. , 1.5, 2. , 2.5, 3. ])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
aListTo100=np.arange(1,101).reshape(10,10)/100

In [72]:
aListTo100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [82]:
aListTo100[0:3,5:]

array([[0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.26, 0.27, 0.28, 0.29, 0.3 ]])