In [1]:
import numpy as np

In [2]:
arr=[1,2,3,4,5]

In [3]:
arrnp=np.array(arr)

In [4]:
arrnp

array([1, 2, 3, 4, 5])

In [5]:
arng=np.arange(0,500,10)

In [6]:
arng

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490])

In [24]:
arng.reshape(5,10)

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490]])

In [25]:
arng.argmax()

49

In [26]:
arng.argmin()

0

In [27]:
arng.max()

490

In [28]:
arng.min()

0

In [29]:
arng.mean()

245.0

In [30]:
arng.any()

True

In [31]:
arng.all()

False

In [37]:
arng.argpartition(1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)

In [38]:
arng.dtype

dtype('int32')

In [49]:
arng.item(20)

200

In [50]:
arng[arng>200]

array([210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330,
       340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460,
       470, 480, 490])

In [51]:
arng[0:5]

array([ 0, 10, 20, 30, 40])

In [10]:
rm=np.random.rand(2,10)

In [11]:
rm

array([[0.29563644, 0.77239267, 0.62675892, 0.92218036, 0.71276054,
        0.42470052, 0.83129439, 0.35308976, 0.25052729, 0.69847719],
       [0.16289004, 0.48553167, 0.54914813, 0.38623188, 0.61174664,
        0.53684061, 0.48601383, 0.26389093, 0.55635385, 0.40724949]])

In [16]:
rmInt=np.random.randint(1,500)

In [17]:
rmInt

77

In [21]:
zero=np.zeros(20)

In [22]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [ ]:
one=np.